print("Para calcular a densidade digite as númerações a seguir:")
massa=input("Digite o valor da massa:")
volume=input("Digite o valor do volume:")
massa=float(massa)
volume=float(volume)
densidade=(massa/volume)
densidade=float(densidade)
densidade=str(densidade)
print("O valor da densidade é: " + densidade)
